FROM alpine:3.18.3

RUN apk add --no-cache openjdk17 maven

WORKDIR /app

COPY . .

COPY settings.xml /root/.m2/settings.xml

RUN mvn clean package

FROM alpine:3.18.3

RUN apk add --no-cache openjdk17

WORKDIR /app

COPY --from=0 /app/target/app-0.0.1-SNAPSHOT.jar .

CMD ["/usr/bin/java", "-jar", "app-0.0.1-SNAPSHOT.jar"]
