version: '3'

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/Mongo6-0_MONGO_PRUEBAS
      o: bind
  mongo-config:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/Mongo6-0_MONGO_CONFIG
      o: bind
  mongo-logs:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/Mongo6-0_MONGO_LOGS
      o: bind
  mongo-initdb:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/Mongo6-0_MONGO_INITDB
      o: bind
  mongo-journal:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/Mongo6-0_MONGO_JOURNAL
      o: bind
  mongo-express-data:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/MongoExpress_0_54_MONGO_PRUEBAS
      o: bind

networks:
  mongo-networks:
    driver: bridge

services:
  mongo:
    image: mongo:6.0
    container_name: MONGO_PRUEBAS
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - mongo-logs:/data/logs
      - mongo-initdb:/docker-entrypoint-initdb.d
      - mongo-journal:/data/journal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mongo-networks

  mongo-express:
    image: mongo-express:0.54
    container_name: MONGO_EXPRESS_PRUEBAS
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    volumes:
      - mongo-express-data:/data/db
    networks:
      - mongo-networks