FROM maven:3.8.3-jdk-11 AS build

WORKDIR /app

COPY . .

RUN mvn clean package

FROM adoptopenjdk:11-jre-hotspot-bionic

WORKDIR /app

COPY --from=build /app/target/myapp.jar .

CMD ["java", "-jar", "myapp.jar"]