version: '3.8'

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: /Users/ayrtonaldayrnevesestrada/Documents/Docker/Volumenes/RedisAlpine3_18
      o: bind

networks:
  redis-networks:
    driver: bridge

services:
  redis:
    image: redis:alpine3.18
    container_name: REDIS_ALPINE3_18
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
    volumes:
      - redis-data:/data
    networks:
      - redis-networks
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: REDIS_INSIGHT
    restart: always
    ports:
      - "8002:8001"
    depends_on:
      - redis
    links:
      - redis
    networks:
      - redis-networks
